name: Build Windows EXE
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm install
      - run: npm run dist
      - uses: actions/upload-artifact@v4
        with:
          name: SeowonGame-Windows
          path: dist/SeowonGame.exe
